language: rust
rust:
  - stable
  - beta
  - nightly-2018-01-04
  - nightly
addons:
  apt:
    packages:
      - gcc
      - gfortran
      - libopenblas-dev
script:
 - cargo build && cargo build --features direct_blas
matrix:
  allow_failures:
    - rust: nightly
