language: rust
rust:
  - nightly-2018-01-04
  - nightly
addons:
  apt:
    packages:
      - gcc
      - gfortran
      - libopenblas-dev
script:
  - mv rust-toolchain .no.rust-toolchain
  - cargo build && cargo build --features direct_blas
matrix:
  allow_failures:
    - rust: nightly
