name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (default)
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install gcc gfortran libopenblas-dev
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache: true
    - run: cargo test

