name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test (default)
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install gcc gfortran libopenblas-dev
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
    - uses: actions-rs/cargo@v1
      with:
        command: test
